
package nl.tt_solutions.schemas.ns.rti._1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * Version 1.1 Webservice for submitting Real Time Information to the EDS' Journey Planner.
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "JourneyPlanner", targetNamespace = "http://www.tt-solutions.nl/schemas/NS/RTI/1.1/", wsdlLocation = "file:/home/thomas/Downloads/ovinfo/arnu/si_int_1.1.0%20-%20HPJourneyPlannerServiceInfo.wsdl")
public class JourneyPlanner
    extends Service
{

    private final static URL JOURNEYPLANNER_WSDL_LOCATION;
    private final static WebServiceException JOURNEYPLANNER_EXCEPTION;
    private final static QName JOURNEYPLANNER_QNAME = new QName("http://www.tt-solutions.nl/schemas/NS/RTI/1.1/", "JourneyPlanner");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/thomas/Downloads/ovinfo/arnu/si_int_1.1.0%20-%20HPJourneyPlannerServiceInfo.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        JOURNEYPLANNER_WSDL_LOCATION = url;
        JOURNEYPLANNER_EXCEPTION = e;
    }

    public JourneyPlanner() {
        super(__getWsdlLocation(), JOURNEYPLANNER_QNAME);
    }

    public JourneyPlanner(WebServiceFeature... features) {
        super(__getWsdlLocation(), JOURNEYPLANNER_QNAME, features);
    }

    public JourneyPlanner(URL wsdlLocation) {
        super(wsdlLocation, JOURNEYPLANNER_QNAME);
    }

    public JourneyPlanner(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, JOURNEYPLANNER_QNAME, features);
    }

    public JourneyPlanner(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JourneyPlanner(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns JourneyPlannerSoap
     */
    @WebEndpoint(name = "JourneyPlannerSoap")
    public JourneyPlannerSoap getJourneyPlannerSoap() {
        return super.getPort(new QName("http://www.tt-solutions.nl/schemas/NS/RTI/1.1/", "JourneyPlannerSoap"), JourneyPlannerSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JourneyPlannerSoap
     */
    @WebEndpoint(name = "JourneyPlannerSoap")
    public JourneyPlannerSoap getJourneyPlannerSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.tt-solutions.nl/schemas/NS/RTI/1.1/", "JourneyPlannerSoap"), JourneyPlannerSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (JOURNEYPLANNER_EXCEPTION!= null) {
            throw JOURNEYPLANNER_EXCEPTION;
        }
        return JOURNEYPLANNER_WSDL_LOCATION;
    }

}
