
package nl.tt_solutions.schemas.ns.rti._1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "JourneyPlannerSoap", targetNamespace = "http://www.tt-solutions.nl/schemas/NS/RTI/1.1/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface JourneyPlannerSoap {


    /**
     * 
     * @param parameter
     * @return
     *     returns nl.tt_solutions.schemas.ns.rti._1.GetServiceInfoOut
     */
    @WebMethod(operationName = "GetServiceInfo", action = "urn:#GetServiceInfo")
    @WebResult(name = "GetServiceInfoOut", targetNamespace = "http://www.tt-solutions.nl/schemas/NS/RTI/1.1/", partName = "parameter")
    public GetServiceInfoOut getServiceInfo(
        @WebParam(name = "GetSeviceInfoIn", targetNamespace = "http://www.tt-solutions.nl/schemas/NS/RTI/1.1/", partName = "parameter")
        GetSeviceInfoIn parameter);

    /**
     * 
     * @param parameter
     * @return
     *     returns nl.tt_solutions.schemas.ns.rti._1.GetRtiMonitorOut
     */
    @WebMethod(operationName = "GetRtiMonitor", action = "urn:#GetRtiMonitor")
    @WebResult(name = "GetRtiMonitorOut", targetNamespace = "http://www.tt-solutions.nl/schemas/NS/RTI/1.1/", partName = "parameter")
    public GetRtiMonitorOut getRtiMonitor(
        @WebParam(name = "GetRtiMonitorIn", targetNamespace = "http://www.tt-solutions.nl/schemas/NS/RTI/1.1/", partName = "parameter")
        GetRtiMonitorIn parameter);

    /**
     * 
     * @param parameter
     * @return
     *     returns nl.tt_solutions.schemas.ns.rti._1.GetServiceInfoJitOut
     */
    @WebMethod(operationName = "GetServiceInfoJit", action = "urn:GetServiceInfoJit")
    @WebResult(name = "GetServiceInfoJitOut", targetNamespace = "http://www.tt-solutions.nl/schemas/NS/RTI/1.1/", partName = "parameter")
    public GetServiceInfoJitOut getServiceInfoJit(
        @WebParam(name = "GetServiceInfoJitIn", targetNamespace = "http://www.tt-solutions.nl/schemas/NS/RTI/1.1/", partName = "parameter")
        GetServiceInfoJitIn parameter);

    /**
     * Service definition of function ns__Service
     * 
     * @param parameter
     * @return
     *     returns nl.tt_solutions.schemas.ns.rti._1.PutServiceInfoOut
     */
    @WebMethod(operationName = "PutServiceInfo", action = "urn:#PutServiceInfo")
    @WebResult(name = "PutServiceInfoOut", targetNamespace = "http://www.tt-solutions.nl/schemas/NS/RTI/1.1/", partName = "parameter")
    public PutServiceInfoOut putServiceInfo(
        @WebParam(name = "PutServiceInfoIn", targetNamespace = "http://www.tt-solutions.nl/schemas/NS/RTI/1.1/", partName = "parameter")
        PutServiceInfoIn parameter);

    /**
     * Service definition of function ns__InfraRestriction
     * 
     * @param parameter
     * @return
     *     returns nl.tt_solutions.schemas.ns.rti._1.PutPlatformInfoOut
     */
    @WebMethod(operationName = "PutPlatformInfo", action = "urn:#PutPlatformInfo")
    @WebResult(name = "PutPlatformInfoOut", targetNamespace = "http://www.tt-solutions.nl/schemas/NS/RTI/1.1/", partName = "parameter")
    public PutPlatformInfoOut putPlatformInfo(
        @WebParam(name = "PutPlatformInfoIn", targetNamespace = "http://www.tt-solutions.nl/schemas/NS/RTI/1.1/", partName = "parameter")
        PutPlatformInfoIn parameter);

}
